CREATE TABLE TRAVELAGENCIES (
  TRAVEL_AGENCY_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  CITY VARCHAR(250) NOT NULL,
  PHONE_NUMBER VARCHAR(250) NOT NULL
);

CREATE TABLE CUSTOMERS (
  CUSTOMER_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  LOGIN VARCHAR(250) NOT NULL,
  EMAIL VARCHAR(250) NOT NULL
);

CREATE TABLE HOTELS (
  HOTEL_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  HOTEL_NAME VARCHAR(250) NOT NULL,
  CITY VARCHAR(250) NOT NULL,
  STARS VARCHAR(250) NOT NULL,
  PHONE_NUMBER VARCHAR(250) NOT NULL
);

CREATE TABLE ADDRESSES (
  ADDRESS_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  CUSTOMER_ID INT NOT NULL,
  STREET VARCHAR(250) NOT NULL,
  HOUSE_NR VARCHAR(250) NOT NULL,
  CITY VARCHAR(250) NOT NULL,
  ZIP_CODE VARCHAR(250) NOT NULL,
  PHONE_NR VARCHAR(250) NOT NULL,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE BOOKINGS (
  BOOKING_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  CUSTOMER_ID BIGINT NOT NULL,
  HOTEL_ID BIGINT NOT NULL,
  TRAVELAGENCY_ID BIGINT NOT NULL,
  PRICE decimal(19,2),
  START_DATE date,
  END_DATE date,
  PAYMENT VARCHAR(250) NOT NULL,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
  FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS(HOTEL_ID),
  FOREIGN KEY (TRAVELAGENCY_ID) REFERENCES TRAVELAGENCIES(TRAVEL_AGENCY_ID)
);